// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cyytvuqhzhjczyugvjyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5eXR2dXFoemhqY3p5dWd2anlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NjMxNjYsImV4cCI6MjA2NTEzOTE2Nn0.hryRwlFg9lYtkPURdYV38OfqVJTr5hDaZ_X-5IDGoNA";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);